let
    Source = Excel.Workbook(File.Contents("C:\Path\To\SalesData.xlsx"), null, true),
    SalesData = Source{[Name="Sales"]}[Content],
    ChangedTypes = Table.TransformColumnTypes(SalesData,{
        {"OrderID", type text},
        {"OrderDate", type date},
        {"ProductID", type text},
        {"ProductName", type text},
        {"Category", type text},
        {"Subcategory", type text},
        {"Quantity", Int64.Type},
        {"Revenue", type number},
        {"Cost", type number},
        {"CustomerID", type text},
        {"Region", type text}
    }),
    AddedProfit = Table.AddColumn(ChangedTypes, "Profit", each [Revenue] - [Cost], type number)
in
    AddedProfit
